services:
  frontend:
    image: yaswanth0461/polling-app-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://13.203.183.22:10000
      - NEXT_PUBLIC_WS_URL=ws://13.203.183.22:10000/ws
    depends_on:
      - backend

  backend:
    image: yaswanth0461/polling-app-backend:latest
    ports:
      - "10000:10000"
    env_file:
      - ./backend/.env